repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
            "-rn", # Only display messages
            "-sn", # Don't display the score
            "--rcfile=.pylintrc", # Link to your config file
            "--load-plugins=pylint.extensions.docparams", # Load an extension
          ]

  - repo: https://github.com/ambv/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3
        stages: [pre-commit]

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: ['--config=.flake8']
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        language: system
        entry: pytest -v -s
        always_run: true
        pass_filenames: false
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: powershell -Command "python -m pip freeze > requirements.txt; git add requirements.txt"
        language: system
        pass_filenames: false
        stages: [pre-commit]